### ISSUE TITLE
Silence SSH banners one way or the other

### ISSUE THREAD

**Issue by dagwieers** [shmux/shmux#1]
In a lot of corporate environments SSH is configured to show a banner (usually some legalese warning). It would be nice to offer a way to disable these SSH messages through shmux.

1. One option is just to document to use the ssh `-oLogLevel=ERROR` option, or have it configured in your ~/.ssh/config file (which is what I usually do e.g. on jumphosts)
2. Another option is to hardcode the DEFAULT_RCMD to be `ssh -oLogLevel=ERROR`
3. Or to add another flag that automatically extends the SHMUX_SSH_OPTS with `-oLogLevel=ERROR`

I think all of these could be valid.

**Comment by syrkuit** [comment]
Wish I'd known about this before. I wonder how portable this is though.

**Comment by dagwieers** [comment]
Thanks !
