### ISSUE TITLE
Download tarball?

### ISSUE THREAD

**Issue by ghost** [shmux/shmux#4]
Hi,

I noticed that shmux is now on github.

In the past I used URLs such as:

  http://web.taranis.org/shmux/dist/shmux-1.0.2.tgz

This was very convenient for wget-script and also
determining the program version. Do you think you
could make this on github too? 

Unfortunately I do not know how this is done, but
other github projects have this like so:

  https://github.com/downloads/mpruett/audiofile/audiofile-0.3.6.tar.gz

It would help me quite a bit to have such easy parse-able
files; I can of course use the download button and have a
.zip file but I'd love to use any .tar archive with a fixed URL.

Anyway, if this is unwanted or too much work, just feel free
to close the issue here. Thanks!

**Comment by syrkuit** [comment]
You're looking for https://github.com/shmux/shmux/archive/v1.0.2.tar.gz
